# Einführung in die Pandas-Bibliothek

## Bibliotheken importieren

In [14]:
import pandas as pd

* Check: Pandas wurde geladen durch Ausgabe des pd-Objekts
  * Hinweis: Die Python-Umgebung wird pro Notebook gestartet, damit stellen bereits ausgeführte Zellen Objekte, Funktionen etc. bereit

In [15]:
print(pd)

<module 'pandas' from 'c:\\Users\\raine\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\site-packages\\pandas\\__init__.py'>

## Eigenschaften des Pandas-Objekts

* Hinweis
  * Das pandas-Objekt ist ziemlich unstrukturiert, unübersichtlich, überladen
  * Es wäre besser gewesen, das Pandas-Objekt noch mit Unterobjekten zu strukturieren
     * Beispiel
         * So ist es:
           * pd.read_csv('path')
         * So fände ich es besser:
           * pd.reader.csv('path')
           * pd.statistics.mean

In [16]:
# pd.c # Code Assist in Visual Studio Code

## Exploration von Daten

* Das Einlesen der Daten erfolt mit den read_xyz-Methoden

In [17]:
pd.read_csv('people.csv')

     lastname  firstname  height_cm  weight_kg
0      Müller     Thomas      197.0        NaN
1     Schmidt    Michael      192.0       50.0
2   Schneider    Andreas      191.0        NaN
3     Fischer     Stefan      195.0       70.0
4       Weber  Christian      185.0       73.0
5       Meyer     Markus      183.0       67.0
6      Wagner     Daniel        NaN      116.0
7      Becker      Kevin      193.0      113.0
8      Schulz     Sascha      197.0      117.0
9    Hoffmann       Jens      193.0        NaN
10       Koch     Oliver        NaN       82.0
11      Bauer    Patrick      165.0       93.0
12    Richter        Jan        NaN        NaN
13      Klein     Tobias      168.0       63.0
14       Wolf  Sebastian      165.0        NaN
15   Schröder  Alexander      187.0       64.0
16    Neumann     Dennis        NaN       94.0
17      Braun      Frank        NaN        NaN
18    Schwarz        Tim      176.0       55.0
19     Krüger      Lukas      178.0       58.0

### Exkurs: Out-Zellen und Python-Programme

* Das Ergebnis der letzten Anweisung wird automatisch in den Out-Bereich geschrieben
* Formatierung übernimmt das Notebook speziell für die unterstützten Datentypem
* Das normale print funktioniert, allerdings ist das Ergebnis unformatiert

In [18]:
message = 'Hello'
print(message)
new_message = message + ' World'
new_message

Hello

'Hello World'

* Richtiges Einlesen der Daten
  * Zuweisung an eine DataFrame-Variable

In [19]:
df = pd.read_csv('people.csv')
type(df)

pandas.core.frame.DataFrame

### Methoden des DataFrame

In [20]:
df.head()

    lastname  firstname  height_cm  weight_kg
0     Müller     Thomas      197.0        NaN
1    Schmidt    Michael      192.0       50.0
2  Schneider    Andreas      191.0        NaN
3    Fischer     Stefan      195.0       70.0
4      Weber  Christian      185.0       73.0

In [21]:
df.tail()

    lastname  firstname  height_cm  weight_kg
15  Schröder  Alexander      187.0       64.0
16   Neumann     Dennis        NaN       94.0
17     Braun      Frank        NaN        NaN
18   Schwarz        Tim      176.0       55.0
19    Krüger      Lukas      178.0       58.0

In [22]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 20 entries, 0 to 19
Data columns (total 4 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   lastname   20 non-null     object
 1   firstname  20 non-null     object
 2   height_cm  15 non-null     float64
 3   weight_kg  14 non-null     float64
dtypes: float64(2), object(2)
memory usage: 772.0+ bytes

In [23]:
df.describe()

        height_cm   weight_kg
count   15.000000   14.000000
mean   184.333333   79.642857
std     11.405930   23.193524
min    165.000000   50.000000
25%    177.000000   63.250000
50%    187.000000   71.500000
75%    193.000000   93.750000
max    197.000000  117.000000

* DataFrame Operationen

In [24]:
# f'{df['lastname']}  {df['firstname']}' # Keine String-Interpolation
calculated_series = df['firstname'] + " " + df['lastname']
df['fullname'] = calculated_series
df
df['fullname2'] = df['lastname'] + " " + df['firstname']
df 
df['fullname3'] = df.lastname + "->" + df.firstname
df

,lastname,firstname,height_cm,weight_kg,fullname,fullname2,fullname3
0,Müller,Thomas,197.0,NaN,Thomas Müller,Müller Thomas,Müller->Thomas
1,Schmidt,Michael,192.0,50.0,Michael Schmidt,Schmidt Michael,Schmidt->Michael
2,Schneider,Andreas,191.0,NaN,Andreas Schneider,Schneider Andreas,Schneider->Andreas
3,Fischer,Stefan,195.0,70.0,Stefan Fischer,Fischer Stefan,Fischer->Stefan
4,Weber,Christian,185.0,73.0,Christian Weber,Weber Christian,Weber->Christian
5,Meyer,Markus,183.0,67.0,Markus Meyer,Meyer Markus,Meyer->Markus
6,Wagner,Daniel,NaN,116.0,Daniel Wagner,Wagner Daniel,Wagner->Daniel
7,Becker,Kevin,193.0,113.0,Kevin Becker,Becker Kevin,Becker->Kevin
8,Schulz,Sascha,197.0,117.0,Sascha Schulz,Schulz Sascha,Schulz->Sascha
9,Hoffmann,Jens,193.0,NaN,Jens Hoffmann,Hoffmann Jens,Hoffmann->Jens
10,Koch,Oliver,NaN,82.0,Oliver Koch,Koch Oliver,Koch->Oliver
11,Bauer,Patrick,165.0,93.0,Patrick Bauer,Bauer Patrick,Bauer->Patrick
12,Richter,Jan,NaN,NaN,Jan Richter,Richter Jan,Richter->Jan
13,Klein,Tobias,168.0,63.0,Tobias Klein,Klein Tobias,Klein->Tobias
14,Wolf,Sebastian,165.0,NaN,Sebastian Wolf,Wolf Sebastian,Wolf->Sebastian
15,Schröder,Alexander,187.0,64.0,Alexander Schröder,Schröder Alexander,Schröder->Alexander
16,Neumann,Dennis,NaN,94.0,Dennis Neumann,Neumann Dennis,Neumann->Dennis
17,Braun,Frank,NaN,NaN,Frank Braun,Braun Frank,Braun->Frank
18,Schwarz,Tim,176.0,55.0,Tim Schwarz,Schwarz Tim,Schwarz->Tim
19,Krüger,Lukas,178.0,58.0,Lukas Krüger,Krüger Lukas,Krüger->Lukas

* Entfernen von Spalten

In [25]:
# df.drop('fullname3', axis=1, inplace=True)
#df.drop('fullname3', axis=1)
#df

df.drop('fullname3', axis=1)

,lastname,firstname,height_cm,weight_kg,fullname,fullname2
0,Müller,Thomas,197.0,NaN,Thomas Müller,Müller Thomas
1,Schmidt,Michael,192.0,50.0,Michael Schmidt,Schmidt Michael
2,Schneider,Andreas,191.0,NaN,Andreas Schneider,Schneider Andreas
3,Fischer,Stefan,195.0,70.0,Stefan Fischer,Fischer Stefan
4,Weber,Christian,185.0,73.0,Christian Weber,Weber Christian
5,Meyer,Markus,183.0,67.0,Markus Meyer,Meyer Markus
6,Wagner,Daniel,NaN,116.0,Daniel Wagner,Wagner Daniel
7,Becker,Kevin,193.0,113.0,Kevin Becker,Becker Kevin
8,Schulz,Sascha,197.0,117.0,Sascha Schulz,Schulz Sascha
9,Hoffmann,Jens,193.0,NaN,Jens Hoffmann,Hoffmann Jens
10,Koch,Oliver,NaN,82.0,Oliver Koch,Koch Oliver
11,Bauer,Patrick,165.0,93.0,Patrick Bauer,Bauer Patrick
12,Richter,Jan,NaN,NaN,Jan Richter,Richter Jan
13,Klein,Tobias,168.0,63.0,Tobias Klein,Klein Tobias
14,Wolf,Sebastian,165.0,NaN,Sebastian Wolf,Wolf Sebastian
15,Schröder,Alexander,187.0,64.0,Alexander Schröder,Schröder Alexander
16,Neumann,Dennis,NaN,94.0,Dennis Neumann,Neumann Dennis
17,Braun,Frank,NaN,NaN,Frank Braun,Braun Frank
18,Schwarz,Tim,176.0,55.0,Tim Schwarz,Schwarz Tim
19,Krüger,Lukas,178.0,58.0,Lukas Krüger,Krüger Lukas

In [26]:
df['bmi'] = df.weight_kg / (df.height_cm*df.height_cm) * 10000
df

,lastname,firstname,height_cm,weight_kg,fullname,fullname2,fullname3,bmi
0,Müller,Thomas,197.0,NaN,Thomas Müller,Müller Thomas,Müller->Thomas,NaN
1,Schmidt,Michael,192.0,50.0,Michael Schmidt,Schmidt Michael,Schmidt->Michael,13.563368
2,Schneider,Andreas,191.0,NaN,Andreas Schneider,Schneider Andreas,Schneider->Andreas,NaN
3,Fischer,Stefan,195.0,70.0,Stefan Fischer,Fischer Stefan,Fischer->Stefan,18.408941
4,Weber,Christian,185.0,73.0,Christian Weber,Weber Christian,Weber->Christian,21.329438
5,Meyer,Markus,183.0,67.0,Markus Meyer,Meyer Markus,Meyer->Markus,20.006569
6,Wagner,Daniel,NaN,116.0,Daniel Wagner,Wagner Daniel,Wagner->Daniel,NaN
7,Becker,Kevin,193.0,113.0,Kevin Becker,Becker Kevin,Becker->Kevin,30.336385
8,Schulz,Sascha,197.0,117.0,Sascha Schulz,Schulz Sascha,Schulz->Sascha,30.147646
9,Hoffmann,Jens,193.0,NaN,Jens Hoffmann,Hoffmann Jens,Hoffmann->Jens,NaN
10,Koch,Oliver,NaN,82.0,Oliver Koch,Koch Oliver,Koch->Oliver,NaN
11,Bauer,Patrick,165.0,93.0,Patrick Bauer,Bauer Patrick,Bauer->Patrick,34.159780
12,Richter,Jan,NaN,NaN,Jan Richter,Richter Jan,Richter->Jan,NaN
13,Klein,Tobias,168.0,63.0,Tobias Klein,Klein Tobias,Klein->Tobias,22.321429
14,Wolf,Sebastian,165.0,NaN,Sebastian Wolf,Wolf Sebastian,Wolf->Sebastian,NaN
15,Schröder,Alexander,187.0,64.0,Alexander Schröder,Schröder Alexander,Schröder->Alexander,18.301925
16,Neumann,Dennis,NaN,94.0,Dennis Neumann,Neumann Dennis,Neumann->Dennis,NaN
17,Braun,Frank,NaN,NaN,Frank Braun,Braun Frank,Braun->Frank,NaN
18,Schwarz,Tim,176.0,55.0,Tim Schwarz,Schwarz Tim,Schwarz->Tim,17.755682
19,Krüger,Lukas,178.0,58.0,Lukas Krüger,Krüger Lukas,Krüger->Lukas,18.305769

### Cleanup

In [31]:
df.fillna(4711)

,lastname,firstname,height_cm,weight_kg,fullname,fullname2,fullname3,bmi
0,Müller,Thomas,197.0,4711.0,Thomas Müller,Müller Thomas,Müller->Thomas,4711.000000
1,Schmidt,Michael,192.0,50.0,Michael Schmidt,Schmidt Michael,Schmidt->Michael,13.563368
2,Schneider,Andreas,191.0,4711.0,Andreas Schneider,Schneider Andreas,Schneider->Andreas,4711.000000
3,Fischer,Stefan,195.0,70.0,Stefan Fischer,Fischer Stefan,Fischer->Stefan,18.408941
4,Weber,Christian,185.0,73.0,Christian Weber,Weber Christian,Weber->Christian,21.329438
5,Meyer,Markus,183.0,67.0,Markus Meyer,Meyer Markus,Meyer->Markus,20.006569
6,Wagner,Daniel,4711.0,116.0,Daniel Wagner,Wagner Daniel,Wagner->Daniel,4711.000000
7,Becker,Kevin,193.0,113.0,Kevin Becker,Becker Kevin,Becker->Kevin,30.336385
8,Schulz,Sascha,197.0,117.0,Sascha Schulz,Schulz Sascha,Schulz->Sascha,30.147646
9,Hoffmann,Jens,193.0,4711.0,Jens Hoffmann,Hoffmann Jens,Hoffmann->Jens,4711.000000
10,Koch,Oliver,4711.0,82.0,Oliver Koch,Koch Oliver,Koch->Oliver,4711.000000
11,Bauer,Patrick,165.0,93.0,Patrick Bauer,Bauer Patrick,Bauer->Patrick,34.159780
12,Richter,Jan,4711.0,4711.0,Jan Richter,Richter Jan,Richter->Jan,4711.000000
13,Klein,Tobias,168.0,63.0,Tobias Klein,Klein Tobias,Klein->Tobias,22.321429
14,Wolf,Sebastian,165.0,4711.0,Sebastian Wolf,Wolf Sebastian,Wolf->Sebastian,4711.000000
15,Schröder,Alexander,187.0,64.0,Alexander Schröder,Schröder Alexander,Schröder->Alexander,18.301925
16,Neumann,Dennis,4711.0,94.0,Dennis Neumann,Neumann Dennis,Neumann->Dennis,4711.000000
17,Braun,Frank,4711.0,4711.0,Frank Braun,Braun Frank,Braun->Frank,4711.000000
18,Schwarz,Tim,176.0,55.0,Tim Schwarz,Schwarz Tim,Schwarz->Tim,17.755682
19,Krüger,Lukas,178.0,58.0,Lukas Krüger,Krüger Lukas,Krüger->Lukas,18.305769

### Exkurs: Selektion von Daten im DataFrame mit Pandas

* Beispiel: Selektion nach Körpergröße

In [49]:
criteria_series = df['height_cm'] > 190
df[criteria_series]

,lastname,firstname,height_cm,weight_kg,fullname,fullname2,fullname3,bmi
0,Müller,Thomas,197.0,NaN,Thomas Müller,Müller Thomas,Müller->Thomas,NaN
1,Schmidt,Michael,192.0,50.0,Michael Schmidt,Schmidt Michael,Schmidt->Michael,13.563368
2,Schneider,Andreas,191.0,NaN,Andreas Schneider,Schneider Andreas,Schneider->Andreas,NaN
3,Fischer,Stefan,195.0,70.0,Stefan Fischer,Fischer Stefan,Fischer->Stefan,18.408941
7,Becker,Kevin,193.0,113.0,Kevin Becker,Becker Kevin,Becker->Kevin,30.336385
8,Schulz,Sascha,197.0,117.0,Sascha Schulz,Schulz Sascha,Schulz->Sascha,30.147646
9,Hoffmann,Jens,193.0,NaN,Jens Hoffmann,Hoffmann Jens,Hoffmann->Jens,NaN

In [47]:
df[df['height_cm'] > 190]

,lastname,firstname,height_cm,weight_kg,fullname,fullname2,fullname3,bmi
0,Müller,Thomas,197.0,NaN,Thomas Müller,Müller Thomas,Müller->Thomas,NaN
1,Schmidt,Michael,192.0,50.0,Michael Schmidt,Schmidt Michael,Schmidt->Michael,13.563368
2,Schneider,Andreas,191.0,NaN,Andreas Schneider,Schneider Andreas,Schneider->Andreas,NaN
3,Fischer,Stefan,195.0,70.0,Stefan Fischer,Fischer Stefan,Fischer->Stefan,18.408941
7,Becker,Kevin,193.0,113.0,Kevin Becker,Becker Kevin,Becker->Kevin,30.336385
8,Schulz,Sascha,197.0,117.0,Sascha Schulz,Schulz Sascha,Schulz->Sascha,30.147646
9,Hoffmann,Jens,193.0,NaN,Jens Hoffmann,Hoffmann Jens,Hoffmann->Jens,NaN