# Titanic Data

## Import der benötigten Bibliotheken

In [33]:
import pandas as pd

## Einladen

In [34]:
titanic_df_part1 = pd.read_csv('titanic.csv')
titanic_df_part1.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S

In [35]:
titanic_df_part2_incomplete = pd.read_csv('titanic_part2_incomplete.csv')
titanic_df_part2_incomplete.head()

,PassengerId,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,951,1,"Chaudanson, Miss. Victorine",female,36.0,0,0,PC 17608,262.3750,B61,C
1,952,3,"Dika, Mr. Mirko",male,17.0,0,0,349232,7.8958,NaN,S
2,953,2,"McCrae, Mr. Arthur Gordon",male,32.0,0,0,237216,13.5000,NaN,S
3,954,3,"Bjorklund, Mr. Ernst Herbert",male,18.0,0,0,347090,7.7500,NaN,S
4,955,3,"Bradley, Miss. Bridget Delia",female,22.0,0,0,334914,7.7250,NaN,Q

In [36]:
titanic_df_part2_survival = pd.read_csv('titanic_part2_survival.csv')
titanic_df_part2_survival.head()

   PassengerId  Survived
0          951         0
1          952         0
2          953         0
3          954         0
4          955         0

## Zusammenfassen der Datensätze

In [37]:
titanic_df_part2 = pd.merge(titanic_df_part2_incomplete, titanic_df_part2_survival, how='inner', on='PassengerId')
titanic_df_part2.head()

,PassengerId,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked,Survived
0,951,1,"Chaudanson, Miss. Victorine",female,36.0,0,0,PC 17608,262.3750,B61,C,0
1,952,3,"Dika, Mr. Mirko",male,17.0,0,0,349232,7.8958,NaN,S,0
2,953,2,"McCrae, Mr. Arthur Gordon",male,32.0,0,0,237216,13.5000,NaN,S,0
3,954,3,"Bjorklund, Mr. Ernst Herbert",male,18.0,0,0,347090,7.7500,NaN,S,0
4,955,3,"Bradley, Miss. Bridget Delia",female,22.0,0,0,334914,7.7250,NaN,Q,0

In [38]:
df = pd.concat([titanic_df_part1, titanic_df_part2], ignore_index=True)
df

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S
...,...,...,...,...,...,...,...,...,...,...,...,...
1303,1305,0,3,"Spector, Mr. Woolf",male,NaN,0,0,A.5. 3236,8.0500,NaN,S
1304,1306,0,1,"Oliva y Ocana, Dona. Fermina",female,39.0,0,0,PC 17758,108.9000,C105,C
1305,1307,0,3,"Saether, Mr. Simon Sivertsen",male,38.5,0,0,SOTON/O.Q. 3101262,7.2500,NaN,S
1306,1308,0,3,"Ware, Mr. Frederick",male,NaN,0,0,359309,8.0500,NaN,S
1307,1309,1,3,"Peter, Master. Michael J",male,NaN,1,1,2668,22.3583,NaN,C

## Exkurs: Wegsichern des DataFrames

In [39]:
df.to_json('titanic_complete.json', orient='records', indent=2)

## Exploration

In [40]:
df.shape

(1308, 12)

In [41]:
df.columns

Index(['PassengerId', 'Survived', 'Pclass', 'Name', 'Sex', 'Age', 'SibSp',
       'Parch', 'Ticket', 'Fare', 'Cabin', 'Embarked'],
      dtype='object')

### Recherche: Fachliche Bedeutung der Spalten

* PassengerID, Survived, Name, Sex, Age ist selbsterklärend
* Pclass: Zahl entspricht der Klasse
* SibSp : Siblings (Verwandte) und Spouses (Ehepartner)
* Parch: Parents and Children
* Ticket: eindeutige Ticketnummer
* Fare: Ticketpreis
* Embarked: Zustiegspunkt, Southhampton, Queenstown, Cherbourg

## Entfernen überflüssiger Spalten

In [42]:
df.drop(['SibSp', 'Parch', 'Ticket', 'Fare'], axis=1, inplace=True)
df.set_index('PassengerId', inplace=True)
df

,Survived,Pclass,Name,Sex,Age,Cabin,Embarked
PassengerId,,,,,,,
1,0,3,"Braund, Mr. Owen Harris",male,22.0,NaN,S
2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,C85,C
3,1,3,"Heikkinen, Miss. Laina",female,26.0,NaN,S
4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,C123,S
5,0,3,"Allen, Mr. William Henry",male,35.0,NaN,S
...,...,...,...,...,...,...,...
1305,0,3,"Spector, Mr. Woolf",male,NaN,NaN,S
1306,0,1,"Oliva y Ocana, Dona. Fermina",female,39.0,C105,C
1307,0,3,"Saether, Mr. Simon Sivertsen",male,38.5,NaN,S
1308,0,3,"Ware, Mr. Frederick",male,NaN,NaN,S
1309,1,3,"Peter, Master. Michael J",male,NaN,NaN,C

## Gibt es fehlende Daten

In [46]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 1308 entries, 1 to 1309
Data columns (total 7 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   Survived  1308 non-null   int64
 1   Pclass    1308 non-null   int64
 2   Name      1308 non-null   object
 3   Sex       1308 non-null   object
 4   Age       1045 non-null   float64
 5   Cabin     295 non-null    object
 6   Embarked  1306 non-null   object
dtypes: float64(1), int64(2), object(4)
memory usage: 81.8+ KB

## Kandidaten für die Kategorisierung

In [47]:
df.unique()

AttributeError: 'DataFrame' object has no attribute 'unique'