# Die Pandas-Bibliothek

## Überblick

* de facto Standard für Datenanalyse-Programme in Python
* Open Source
  * Lizenzfrei in der Nutzung
  * [Homepage](https://pandas.pydata.org/)
  * [Dokumentation](https://pandas.pydata.org/docs/reference/index.html) 
* Funktionsumfang
  * Unterstützung aller gängiger Datenformate, Lesend und Schreibend
  * Spezielle Collection, der DataFrame
  * Unterstützung von Grafiken = Diagrammen
  * Integration der deskriptiven Statistik, also Mittelwerte, Abweichungen, ...
  * Integration weiterer Bibliotheken, z.B. matplotlib, scikit für Machine Learning

## Installation

In [1]:
pip install pandas

Requirement already satisfied: pandas in c:\users\raine\appdata\local\programs\python\python312\lib\site-packages (2.2.2)
Requirement already satisfied: numpy>=1.26.0 in c:\users\raine\appdata\local\programs\python\python312\lib\site-packages (from pandas) (2.0.0)
Requirement already satisfied: python-dateutil>=2.8.2 in c:\users\raine\appdata\local\programs\python\python312\lib\site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in c:\users\raine\appdata\local\programs\python\python312\lib\site-packages (from pandas) (2024.1)
Requirement already satisfied: tzdata>=2022.7 in c:\users\raine\appdata\local\programs\python\python312\lib\site-packages (from pandas) (2024.1)
Requirement already satisfied: six>=1.5 in c:\users\raine\appdata\local\programs\python\python312\lib\site-packages (from python-dateutil>=2.8.2->pandas) (1.16.0)
Note: you may need to restart the kernel to use updated packages.

[notice] A new release of pip is available: 25.0.1 -> 25.3
[notice] To update, run: python.exe -m pip install --upgrade pip

## Einführung in die Programmierung mit Pandas

### Import

In [4]:
import pandas as pd

### Laden eines CSV-Datensatzes

In [5]:
pd.read_csv('PEOPLE.csv')

     id   firstname lastname  height  weight GENDER
0     1      Stacey   Miller    1.68    92.0      d
1     2       Carla   Gentry    1.68    85.4      d
2     3        Emma  Harding    1.75    98.2      d
3     4    Jeanette    Lopez    1.58    73.8      d
4     5      Edward    White    1.63    68.5      d
..  ...         ...      ...     ...     ...    ...
95   96  Jacqueline   Morris    1.54    99.8      d
96   97       Laura    Smith    1.66    50.1      d
97   98      Steven  Parrish    1.68    99.0      d
98   99     Stephen   Juarez    1.82    93.3      d
99  100    Courtney     Cruz    1.59    75.1      d

[100 rows x 6 columns]

### Laden des Datensatzes und Zuweisung an eine Variable 

* Typ der Variable ist ein Pandas-DataFrame

In [7]:
df = pd.read_csv('PEOPLE.csv')
df

     id   firstname lastname  height  weight GENDER
0     1      Stacey   Miller    1.68    92.0      d
1     2       Carla   Gentry    1.68    85.4      d
2     3        Emma  Harding    1.75    98.2      d
3     4    Jeanette    Lopez    1.58    73.8      d
4     5      Edward    White    1.63    68.5      d
..  ...         ...      ...     ...     ...    ...
95   96  Jacqueline   Morris    1.54    99.8      d
96   97       Laura    Smith    1.66    50.1      d
97   98      Steven  Parrish    1.68    99.0      d
98   99     Stephen   Juarez    1.82    93.3      d
99  100    Courtney     Cruz    1.59    75.1      d

[100 rows x 6 columns]

### Exploration des Datensatzes

* head() und tail()
  * Standard-Größe ist 5
  * head(3)

In [10]:
df.head(3)

   id firstname lastname  height  weight GENDER
0   1    Stacey   Miller    1.68    92.0      d
1   2     Carla   Gentry    1.68    85.4      d
2   3      Emma  Harding    1.75    98.2      d

* info und describe

In [11]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 100 entries, 0 to 99
Data columns (total 6 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   id         100 non-null    int64
 1   firstname  100 non-null    object
 2   lastname   100 non-null    object
 3   height     100 non-null    float64
 4   weight     100 non-null    float64
 5   GENDER     100 non-null    object
dtypes: float64(2), int64(1), object(3)
memory usage: 4.8+ KB

In [12]:
df.describe()

               id      height      weight
count  100.000000  100.000000  100.000000
mean    50.500000    1.739100   77.210000
std     29.011492    0.135945   13.929342
min      1.000000    1.510000   50.100000
25%     25.750000    1.627500   68.250000
50%     50.500000    1.755000   77.000000
75%     75.250000    1.830000   89.700000
max    100.000000    1.990000   99.900000

* Unsaubere Eingangsdaten

In [13]:
dirty_df = pd.read_csv('PEOPLE_dirty.csv')
dirty_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 100 entries, 0 to 99
Data columns (total 6 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   id         100 non-null    int64
 1   firstname  100 non-null    object
 2   lastname   100 non-null    object
 3   height     97 non-null     float64
 4   weight     98 non-null     float64
 5   GENDER     100 non-null    object
dtypes: float64(2), int64(1), object(3)
memory usage: 4.8+ KB

In [14]:
dirty_df = pd.read_csv('PEOPLE_very_dirty.csv')
dirty_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 100 entries, 0 to 99
Data columns (total 6 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   id         100 non-null    int64
 1   firstname  100 non-null    object
 2   lastname   100 non-null    object
 3   height     97 non-null     object
 4   weight     98 non-null     float64
 5   GENDER     100 non-null    object
dtypes: float64(1), int64(1), object(4)
memory usage: 4.8+ KB