# Die Pandas Bibliothek

## Installation

In [ ]:
pip install pandas

## Standard-Imports

In [1]:
import pandas as pd
import numpy as np

### Hinweis

* Pandas unterstützt 2 neue Typen von sehr "cleveren" Collections
  * Series
  * DataFrame
* Die Grundlage dieser neuen Collections sind Numpy-Arrays
  * Speziell auf Performance und Speicherverwaltung optimiert

## Lesen von Daten

### Lesen einer lokalen CSV-Datei

In [2]:
pd.read_csv('people.csv')

                Name  Weight  Height
0       Anna Neumann    55.8   165.0
1         Ben Wagner    78.6   180.0
2        Carla Weber    60.5     NaN
3      David Schmidt    85.5   185.0
4   Elena Zimmermann    52.5   160.0
5      Felix Schäfer    90.5   190.0
6    Gina Zimmermann    65.6   172.0
7    Hannes Hoffmann    72.4   178.0
8        Isabel Koch    58.8   167.0
9        Jonas Bauer    80.3   182.0
10     Klara Schäfer    56.7   166.0
11     Lukas Fischer    76.4   179.0
12       Maria Weber    62.1   171.0
13         Nico Wolf     NaN   187.0
14    Olivia Schäfer     NaN     NaN
15       Paul Müller    79.2   181.0
16     Quinn Neumann    68.8   175.0
17      Ronja Müller     NaN   176.0
18   Samuel Schröder    83.7   184.0
19      Tina Fischer    59.7   168.0

### Hinweise
* Root-Directory ist das aktuelle Verzeichnis, in dem sich das Notebook befindet
* Rückgabewert wird direkt in den Out-Bereich der Zelle geschrieben

## Lokale JSON-Datei

In [3]:
pd.read_json('people.json')

   id    lastname  firstname gender  height
0   1    Sawitzki     Rainer      m     183
1   2       Meier       Hans      m     163
2   3     Metzger      Georg      m     190
3   4     Metzger     Frieda      f     167
4   5    Hoffmann      Hanna      f     155
5   6  Pausenkurt     Pascal      m     177
6   7       Fisch      Wanda      f     164
7   8     Ziegler     Thomas      m     193
8   9        Tost  Franziska      f     177
9  10      Berger       Hans      m     183

### Lesen einer CSV-Datei vom Internet

In [4]:
pd.read_csv('https://raw.githubusercontent.com/lawlesst/vivo-sample-data/refs/heads/master/data/csv/people.csv')

,person_ID,name,first,last,middle,email,phone,fax,title
0,3130,"Burks, Rosella",Rosella,Burks,NaN,BurksR@univ.edu,963.555.1253,963.777.4065,Professor
1,3297,"Avila, Damien",Damien,Avila,NaN,AvilaD@univ.edu,963.555.1352,963.777.7914,Professor
2,3547,"Olsen, Robin",Robin,Olsen,NaN,OlsenR@univ.edu,963.555.1378,963.777.9262,Assistant Professor
3,1538,"Moises, Edgar Estes",Edgar,Moises,Estes,MoisesE@univ.edu,963.555.2731x3565,963.777.8264,Professor
4,2941,"Brian, Heath Pruitt",Heath,Brian,Pruitt,BrianH@univ.edu,963.555.2800,963.777.7249,Associate Curator
5,2401,"Claude, Elvin Haney",Elvin,Claude,Haney,ClaudeE@univ.edu,963.555.2902,963.777.9730,Curator
6,2070,"Mosley, Edmund",Edmund,Mosley,NaN,MosleyE@univ.edu,963.555.2945,963.777.9285,Assistant Professor
7,2561,"Derek, Antoine Mccoy",Antoine,Derek,Mccoy,DerekA@univ.edu,963.555.2992,963.777.5454,Curator
8,1625,"Hawkins, Callie",Callie,Hawkins,NaN,HawkinsC@univ.edu,963.555.3350x6480,963.777.4949,Professor
9,1307,"Pate, Andrea",Andrea,Pate,NaN,PateA@univ.edu,963.555.3723,963.777.5049,Professor
10,2342,"Austin, Liz",Liz,Austin,NaN,AustinL@univ.edu,963.555.4305,963.777.6143,Assistant Professor
11,2755,"Kendrick, Reba Alford",Reba,Kendrick,Alford,KendrickR@univ.edu,963.555.4618x7744,963.777.4371,Associate Curator
12,4150,"Sims, Angelina",Angelina,Sims,NaN,SimsA@univ.edu,963.555.5278,963.777.4400,Professor
13,3544,"Mullins, Kimberly",Kimberly,Mullins,NaN,MullinsK@univ.edu,963.555.5471x1017,963.777.9783,Assistant Professor
14,2096,"Chuck, Lloyd Haney",Lloyd,Chuck,Haney,ChuckL@univ.edu,963.555.5568x2652,963.777.9290,Assistant Professor
15,1089,"Payne, Ladonna",Ladonna,Payne,NaN,PayneL@univ.edu,963.555.5639,963.777.6469,Professor
16,2948,"Baxter, Johnathan Browning",Johnathan,Baxter,Browning,BaxterJ@univ.edu,963.555.5902,963.777.8336,Research Professor
17,4539,"Weiss, Gilbert",Gilbert,Weiss,NaN,WeissG@univ.edu,963.555.5969,963.777.4975,Professor
18,2811,"Deirdre, Florence Barrera",Florence,Deirdre,Barrera,DeirdreF@univ.edu,963.555.6319,963.777.9654,Associate Curator
19,4580,"Fernando, Toby Calderon",Toby,Fernando,Calderon,FernandoT@univ.edu,963.555.6469,963.777.9864,Research Professor
20,2895,"Garrison, Patrica",Patrica,Garrison,NaN,GarrisonP@univ.edu,963.555.6760,963.777.4958,Associate Curator
21,2254,"Effie, Leila Vinson",Leila,Effie,Vinson,EffieL@univ.edu,963.555.6824,963.777.7299,Assistant Professor
22,2389,"Buckley, Rose",Rose,Buckley,NaN,BuckleyR@univ.edu,963.555.6855x5018,963.777.5233,Curator
23,1699,"Stanton, Kathie",Kathie,Stanton,NaN,StantonK@univ.edu,963.555.7095,963.777.1015,Professor
24,1567,"Banks, Shannon",Shannon,Banks,NaN,BanksS@univ.edu,963.555.7198,963.777.6979,Professor
25,3066,"Barnes, Cleo",Cleo,Barnes,NaN,BarnesC@univ.edu,963.555.7463x7335,963.777.1583,Research Professor
26,2426,"Brady, Nellie",Nellie,Brady,NaN,BradyN@univ.edu,963.555.7569,963.777.7218,Curator
27,2217,"Katheryn, Ruben Holt",Ruben,Katheryn,Holt,KatherynR@univ.edu,963.555.7578,963.777.3969,Assistant Professor
28,1968,"Michael, Dianne",Dianne,Michael,NaN,MichaelD@univ.edu,963.555.7592,963.777.9960,Assistant Professor
29,3012,"Grant, Adam",Adam,Grant,NaN,GrantA@univ.edu,963.555.7775,963.777.8115,Research Professor
30,1824,"Head, Kurtis",Kurtis,Head,NaN,HeadK@univ.edu,963.555.7882,963.777.6348,Professor
31,3929,"Berger, Jami",Jami,Berger,NaN,BergerJ@univ.edu,963.555.8158,963.777.5650,Research Professor
32,2682,"Earline, Jaime Fitzgerald",Jaime,Earline,Fitzgerald,EarlineJ@univ.edu,963.555.8357,963.777.4114,Associate Curator
33,3112,"Evelyn, Summer Frost",Summer,Evelyn,Frost,EvelynS@univ.edu,963.555.8895,963.777.5730,Professor
34,2303,"Quentin, Sam Hyde",Sam,Quentin,Hyde,QuentinS@univ.edu,963.555.8921,963.777.2712,Assistant Professor
35,3903,"Dunlap, Ann",Ann,Dunlap,NaN,DunlapA@univ.edu,963.555.9067,963.777.4290,Assistant Professor
36,3095,"Shields, Rich Pena",Rich,Shields,Pena,ShieldsR@univ.edu,963.555.9197,963.777.7215,Professor
37,2383,"Page, Winnie",Winnie,Page,NaN,PageW@univ.edu,963.555.9366,963.777.3202,Curator
38,2146,"Sparks, Ezra",Ezra,Sparks,NaN,SparksE@univ.edu,963.555.9390,963.777.9273,Assistant Professor
39,3958,"Kaufman, Elba",Elba,Kaufman,NaN,KaufmanE@univ.edu,963.555.9507,963.777.3298,Professor

## Lesen eines RESTful WebServices

In [6]:
pd.read_json('http://javacream.eu:8080/people')

      id        lastname  firstname gender  height
0      1        Sawitzki     Rainer      m     183
1      2           Meier       Hans      m     163
2      3         Metzger      Georg      m     190
3      4         Metzger     Frieda      f     167
4      5        Hoffmann      Hanna      f     155
5      6      Pausenkurt     Pascal      m     177
6      7           Fisch      Wanda      f     164
7      8         Ziegler     Thomas      m     193
8      9            Tost  Franziska      f     177
9     10          Berger       Hans      m     183
10   100  Mujsteerperson     Hannah      d     177
11   101  Mujsteerperson       Hans      d     167
12   666          Christ       Anti      d     247
13  4711    Musterperson     Hannah      w     170
14  4712    Musterperson     Hannah      w     170

### Lesen aus einer Datenbank

In [7]:
# pip install mysql-connector-python
import mysql.connector

connection = mysql.connector.connect(
    host='javacream.eu',
    port=3406, 
    user='user',
    password='user', 
    database='javacream'
)

pd.read_sql('select * from PEOPLE', connection)

C:\Users\raine\AppData\Local\Temp\ipykernel_3152\3125873755.py:12: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  pd.read_sql('select * from PEOPLE', connection)

     id   firstname lastname  height  weight GENDER
0     1      Stacey   Miller    1.68    92.0      d
1     2       Carla   Gentry    1.68    85.4      d
2     3        Emma  Harding    1.75    98.2      d
3     4    Jeanette    Lopez    1.58    73.8      d
4     5      Edward    White    1.63    68.5      d
..  ...         ...      ...     ...     ...    ...
95   96  Jacqueline   Morris    1.54    99.8      d
96   97       Laura    Smith    1.66    50.1      d
97   98      Steven  Parrish    1.68    99.0      d
98   99     Stephen   Juarez    1.82    93.3      d
99  100    Courtney     Cruz    1.59    75.1      d

[100 rows x 6 columns]

## Der DataFrame

In [12]:
df = pd.read_csv('people.csv')
df.head(3) # default = 5

           Name  Weight  Height
0  Anna Neumann    55.8   165.0
1    Ben Wagner    78.6   180.0
2   Carla Weber    60.5     NaN

### Hinweis
* Jeder DataFrame hat einen Index
* Dieser Index identifiziert eine Zeile des DataFrames
* Im Standard eine fortlaufende Nummer
* Die Spalten werden ebenfalls identifizierbar gemacht über eindeutige Spaltennamen
* Als Index kann aber auch eine andere Spalte gesetzt werden
    * Zugriff auf eine Spalte erfolgt wie bei einem Dictionary über den Namen der Spalte

In [13]:
df.set_index('Name')

                  Weight  Height
Name
Anna Neumann        55.8   165.0
Ben Wagner          78.6   180.0
Carla Weber         60.5     NaN
David Schmidt       85.5   185.0
Elena Zimmermann    52.5   160.0
Felix Schäfer       90.5   190.0
Gina Zimmermann     65.6   172.0
Hannes Hoffmann     72.4   178.0
Isabel Koch         58.8   167.0
Jonas Bauer         80.3   182.0
Klara Schäfer       56.7   166.0
Lukas Fischer       76.4   179.0
Maria Weber         62.1   171.0
Nico Wolf            NaN   187.0
Olivia Schäfer       NaN     NaN
Paul Müller         79.2   181.0
Quinn Neumann       68.8   175.0
Ronja Müller         NaN   176.0
Samuel Schröder     83.7   184.0
Tina Fischer        59.7   168.0

### Hinweis
* Viele Methoden eines DataFrames scheinen den DataFrame zu verändern
* Das ist aber nicht der Fall, es wird im Standard immer ein neuer DataFrame zurückgegeben, der Original-DataFrame bleibt unverändert
  * Es gibt einen Parameter inplace. Falls dieser auf True gesetzt ist, wird der Original-DataFrame verändert
    * Vorsicht, damit kann es passieren, dass Zellen nicht beliebig oft ausgeführt werden können

In [14]:
df

                Name  Weight  Height
0       Anna Neumann    55.8   165.0
1         Ben Wagner    78.6   180.0
2        Carla Weber    60.5     NaN
3      David Schmidt    85.5   185.0
4   Elena Zimmermann    52.5   160.0
5      Felix Schäfer    90.5   190.0
6    Gina Zimmermann    65.6   172.0
7    Hannes Hoffmann    72.4   178.0
8        Isabel Koch    58.8   167.0
9        Jonas Bauer    80.3   182.0
10     Klara Schäfer    56.7   166.0
11     Lukas Fischer    76.4   179.0
12       Maria Weber    62.1   171.0
13         Nico Wolf     NaN   187.0
14    Olivia Schäfer     NaN     NaN
15       Paul Müller    79.2   181.0
16     Quinn Neumann    68.8   175.0
17      Ronja Müller     NaN   176.0
18   Samuel Schröder    83.7   184.0
19      Tina Fischer    59.7   168.0

In [15]:
df2 = df.set_index('Name')
df2

                  Weight  Height
Name
Anna Neumann        55.8   165.0
Ben Wagner          78.6   180.0
Carla Weber         60.5     NaN
David Schmidt       85.5   185.0
Elena Zimmermann    52.5   160.0
Felix Schäfer       90.5   190.0
Gina Zimmermann     65.6   172.0
Hannes Hoffmann     72.4   178.0
Isabel Koch         58.8   167.0
Jonas Bauer         80.3   182.0
Klara Schäfer       56.7   166.0
Lukas Fischer       76.4   179.0
Maria Weber         62.1   171.0
Nico Wolf            NaN   187.0
Olivia Schäfer       NaN     NaN
Paul Müller         79.2   181.0
Quinn Neumann       68.8   175.0
Ronja Müller         NaN   176.0
Samuel Schröder     83.7   184.0
Tina Fischer        59.7   168.0

In [23]:
df2.rename(columns={'Weight': 'PERSON_WEIGHT'}, inplace=True)
df2

                  PERSON_WEIGHT  Height
Name
Anna Neumann               55.8   165.0
Ben Wagner                 78.6   180.0
Carla Weber                60.5     NaN
David Schmidt              85.5   185.0
Elena Zimmermann           52.5   160.0
Felix Schäfer              90.5   190.0
Gina Zimmermann            65.6   172.0
Hannes Hoffmann            72.4   178.0
Isabel Koch                58.8   167.0
Jonas Bauer                80.3   182.0
Klara Schäfer              56.7   166.0
Lukas Fischer              76.4   179.0
Maria Weber                62.1   171.0
Nico Wolf                   NaN   187.0
Olivia Schäfer              NaN     NaN
Paul Müller                79.2   181.0
Quinn Neumann              68.8   175.0
Ronja Müller                NaN   176.0
Samuel Schröder            83.7   184.0
Tina Fischer               59.7   168.0

## DataFrame-Methoden zur Daten-Exploration

In [24]:
df.shape

(20, 3)

In [25]:
df.columns

Index(['Name', 'Weight', 'Height'], dtype='object')

### Hinweis
* dtype = DataType
* Grobe Kategorisierung
  * Ganzzahlen
  * Gleitkommazahlen
  * Boolean
  * Rest ist 'object'

In [26]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 20 entries, 0 to 19
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   Name    20 non-null     object
 1   Weight  17 non-null     float64
 2   Height  18 non-null     float64
dtypes: float64(2), object(1)
memory usage: 612.0+ bytes

In [28]:
df.isna().sum()

Name      0
Weight    3
Height    2
dtype: int64

In [ ]:
height_column = df['Height']
selection = height_column.isna()
df[selection]

              Name  Weight  Height
2      Carla Weber    60.5     NaN
14  Olivia Schäfer     NaN     NaN

In [34]:
df[df['Weight'].isna()]

              Name  Weight  Height
13       Nico Wolf     NaN   187.0
14  Olivia Schäfer     NaN     NaN
17    Ronja Müller     NaN   176.0

In [36]:
height_column = df['Height']
selection = height_column > 180
df[selection]

               Name  Weight  Height
3     David Schmidt    85.5   185.0
5     Felix Schäfer    90.5   190.0
9       Jonas Bauer    80.3   182.0
13        Nico Wolf     NaN   187.0
15      Paul Müller    79.2   181.0
18  Samuel Schröder    83.7   184.0

In [38]:
df[df['Weight'] > 90]

            Name  Weight  Height
5  Felix Schäfer    90.5   190.0