# Einführung in die Pandas-Bibliothek

Pandas = Excel für Python

## Bibliotheken importieren

In [33]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plot

### Hinweis
* Numpy ist eine unabhängige Bibliothek
* diese stellt hochoptimierte neue Collections zur Verfügung
  * die Existenz dieser Collections ist für die Anwendung aber in den allermeisten Fällen transparent
  * Die Standard-Collections sind für normale Anwendungsprogrammierung völlig genügend

### Das Pandas-Object

In [34]:
print(pd)

<module 'pandas' from 'c:\\Users\\raine\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\site-packages\\pandas\\__init__.py'>

### Eigenschaften des Pandas-Objekts
* Hinweis
  * Dieses Objekt ist ziemlich unstrukturiert, unübersichtlich, überladen
    * Besser wäre gewesen pd.readers.read_csv(...)
* Primäre Aufgabe ist das Einlesen von Daten

### Datenquellen

* Dateien
  * Reichhaltiger Satz von Dateiformaten
  * Lokation ist ein lokales Dateisystem oder ein REST-Endpoint
* Datenbanksysteme

In [35]:
pd.read_csv('people.csv')

     lastname  firstname  height_cm  weight_kg
0      Müller     Thomas      197.0        NaN
1     Schmidt    Michael      192.0       50.0
2   Schneider    Andreas      191.0        NaN
3     Fischer     Stefan      195.0       70.0
4       Weber  Christian      185.0       73.0
5       Meyer     Markus      183.0       67.0
6      Wagner     Daniel        NaN      116.0
7      Becker      Kevin      193.0      113.0
8      Schulz     Sascha      197.0      117.0
9    Hoffmann       Jens      193.0        NaN
10       Koch     Oliver        NaN       82.0
11      Bauer    Patrick      165.0       93.0
12    Richter        Jan        NaN        NaN
13      Klein     Tobias      168.0       63.0
14       Wolf  Sebastian      165.0        NaN
15   Schröder  Alexander      187.0       64.0
16    Neumann     Dennis        NaN       94.0
17      Braun      Frank        NaN        NaN
18    Schwarz        Tim      176.0       55.0
19     Krüger      Lukas      178.0       58.0

In [36]:
pd.read_json('people.json')

   id    lastname  firstname gender  height
0   1    Sawitzki     Rainer      m     183
1   2       Meier       Hans      m     163
2   3     Metzger      Georg      m     190
3   4     Metzger     Frieda      f     167
4   5    Hoffmann      Hanna      f     155
5   6  Pausenkurt     Pascal      m     177
6   7       Fisch      Wanda      f     164
7   8     Ziegler     Thomas      m     193
8   9        Tost  Franziska      f     177
9  10      Berger       Hans      m     183

In [37]:
pd.read_json('http://javacream.eu:8080/people')

   id    lastname  firstname gender  height
0   1    Sawitzki     Rainer      m     183
1   2       Meier       Hans      m     163
2   3     Metzger      Georg      m     190
3   4     Metzger     Frieda      f     167
4   5    Hoffmann      Hanna      f     155
5   6  Pausenkurt     Pascal      m     177
6   7       Fisch      Wanda      f     164
7   8     Ziegler     Thomas      m     193
8   9        Tost  Franziska      f     177
9  10      Berger       Hans      m     183

In [38]:
pd.read_csv('https://raw.githubusercontent.com/lawlesst/vivo-sample-data/refs/heads/master/data/csv/people.csv')

,person_ID,name,first,last,middle,email,phone,fax,title
0,3130,"Burks, Rosella",Rosella,Burks,NaN,BurksR@univ.edu,963.555.1253,963.777.4065,Professor
1,3297,"Avila, Damien",Damien,Avila,NaN,AvilaD@univ.edu,963.555.1352,963.777.7914,Professor
2,3547,"Olsen, Robin",Robin,Olsen,NaN,OlsenR@univ.edu,963.555.1378,963.777.9262,Assistant Professor
3,1538,"Moises, Edgar Estes",Edgar,Moises,Estes,MoisesE@univ.edu,963.555.2731x3565,963.777.8264,Professor
4,2941,"Brian, Heath Pruitt",Heath,Brian,Pruitt,BrianH@univ.edu,963.555.2800,963.777.7249,Associate Curator
5,2401,"Claude, Elvin Haney",Elvin,Claude,Haney,ClaudeE@univ.edu,963.555.2902,963.777.9730,Curator
6,2070,"Mosley, Edmund",Edmund,Mosley,NaN,MosleyE@univ.edu,963.555.2945,963.777.9285,Assistant Professor
7,2561,"Derek, Antoine Mccoy",Antoine,Derek,Mccoy,DerekA@univ.edu,963.555.2992,963.777.5454,Curator
8,1625,"Hawkins, Callie",Callie,Hawkins,NaN,HawkinsC@univ.edu,963.555.3350x6480,963.777.4949,Professor
9,1307,"Pate, Andrea",Andrea,Pate,NaN,PateA@univ.edu,963.555.3723,963.777.5049,Professor
10,2342,"Austin, Liz",Liz,Austin,NaN,AustinL@univ.edu,963.555.4305,963.777.6143,Assistant Professor
11,2755,"Kendrick, Reba Alford",Reba,Kendrick,Alford,KendrickR@univ.edu,963.555.4618x7744,963.777.4371,Associate Curator
12,4150,"Sims, Angelina",Angelina,Sims,NaN,SimsA@univ.edu,963.555.5278,963.777.4400,Professor
13,3544,"Mullins, Kimberly",Kimberly,Mullins,NaN,MullinsK@univ.edu,963.555.5471x1017,963.777.9783,Assistant Professor
14,2096,"Chuck, Lloyd Haney",Lloyd,Chuck,Haney,ChuckL@univ.edu,963.555.5568x2652,963.777.9290,Assistant Professor
15,1089,"Payne, Ladonna",Ladonna,Payne,NaN,PayneL@univ.edu,963.555.5639,963.777.6469,Professor
16,2948,"Baxter, Johnathan Browning",Johnathan,Baxter,Browning,BaxterJ@univ.edu,963.555.5902,963.777.8336,Research Professor
17,4539,"Weiss, Gilbert",Gilbert,Weiss,NaN,WeissG@univ.edu,963.555.5969,963.777.4975,Professor
18,2811,"Deirdre, Florence Barrera",Florence,Deirdre,Barrera,DeirdreF@univ.edu,963.555.6319,963.777.9654,Associate Curator
19,4580,"Fernando, Toby Calderon",Toby,Fernando,Calderon,FernandoT@univ.edu,963.555.6469,963.777.9864,Research Professor
20,2895,"Garrison, Patrica",Patrica,Garrison,NaN,GarrisonP@univ.edu,963.555.6760,963.777.4958,Associate Curator
21,2254,"Effie, Leila Vinson",Leila,Effie,Vinson,EffieL@univ.edu,963.555.6824,963.777.7299,Assistant Professor
22,2389,"Buckley, Rose",Rose,Buckley,NaN,BuckleyR@univ.edu,963.555.6855x5018,963.777.5233,Curator
23,1699,"Stanton, Kathie",Kathie,Stanton,NaN,StantonK@univ.edu,963.555.7095,963.777.1015,Professor
24,1567,"Banks, Shannon",Shannon,Banks,NaN,BanksS@univ.edu,963.555.7198,963.777.6979,Professor
25,3066,"Barnes, Cleo",Cleo,Barnes,NaN,BarnesC@univ.edu,963.555.7463x7335,963.777.1583,Research Professor
26,2426,"Brady, Nellie",Nellie,Brady,NaN,BradyN@univ.edu,963.555.7569,963.777.7218,Curator
27,2217,"Katheryn, Ruben Holt",Ruben,Katheryn,Holt,KatherynR@univ.edu,963.555.7578,963.777.3969,Assistant Professor
28,1968,"Michael, Dianne",Dianne,Michael,NaN,MichaelD@univ.edu,963.555.7592,963.777.9960,Assistant Professor
29,3012,"Grant, Adam",Adam,Grant,NaN,GrantA@univ.edu,963.555.7775,963.777.8115,Research Professor
30,1824,"Head, Kurtis",Kurtis,Head,NaN,HeadK@univ.edu,963.555.7882,963.777.6348,Professor
31,3929,"Berger, Jami",Jami,Berger,NaN,BergerJ@univ.edu,963.555.8158,963.777.5650,Research Professor
32,2682,"Earline, Jaime Fitzgerald",Jaime,Earline,Fitzgerald,EarlineJ@univ.edu,963.555.8357,963.777.4114,Associate Curator
33,3112,"Evelyn, Summer Frost",Summer,Evelyn,Frost,EvelynS@univ.edu,963.555.8895,963.777.5730,Professor
34,2303,"Quentin, Sam Hyde",Sam,Quentin,Hyde,QuentinS@univ.edu,963.555.8921,963.777.2712,Assistant Professor
35,3903,"Dunlap, Ann",Ann,Dunlap,NaN,DunlapA@univ.edu,963.555.9067,963.777.4290,Assistant Professor
36,3095,"Shields, Rich Pena",Rich,Shields,Pena,ShieldsR@univ.edu,963.555.9197,963.777.7215,Professor
37,2383,"Page, Winnie",Winnie,Page,NaN,PageW@univ.edu,963.555.9366,963.777.3202,Curator
38,2146,"Sparks, Ezra",Ezra,Sparks,NaN,SparksE@univ.edu,963.555.9390,963.777.9273,Assistant Professor
39,3958,"Kaufman, Elba",Elba,Kaufman,NaN,KaufmanE@univ.edu,963.555.9507,963.777.3298,Professor

In [39]:
import mysql.connector

HOST = 'javacream.eu'
PORT = 3406
DATABASE_NAME = 'javacream'
USER = 'user'
PWD = 'user'

connection = mysql.connector.connect(
    host=HOST, 
    port = PORT,
    database = DATABASE_NAME,
    user = USER,
    password = PWD
    )
sql_statement = 'select * from PEOPLE'
pd.read_sql(sql_statement, connection)

C:\Users\raine\AppData\Local\Temp\ipykernel_6632\3750414836.py:17: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  pd.read_sql(sql_statement, connection)

     id   firstname lastname  height  weight
0     1      Stacey   Miller    1.68    92.0
1     2       Carla   Gentry    1.68    85.4
2     3        Emma  Harding    1.75    98.2
3     4    Jeanette    Lopez    1.58    73.8
4     5      Edward    White    1.63    68.5
..  ...         ...      ...     ...     ...
95   96  Jacqueline   Morris    1.54    99.8
96   97       Laura    Smith    1.66    50.1
97   98      Steven  Parrish    1.68    99.0
98   99     Stephen   Juarez    1.82    93.3
99  100    Courtney     Cruz    1.59    75.1

[100 rows x 5 columns]

## Der Pandas DataFrame

* Rückgabewert der Leseoperation von Pandas

In [60]:
df = pd.read_csv('people.csv')

### Exploration

In [41]:
df.head()

    lastname  firstname  height_cm  weight_kg
0     Müller     Thomas      197.0        NaN
1    Schmidt    Michael      192.0       50.0
2  Schneider    Andreas      191.0        NaN
3    Fischer     Stefan      195.0       70.0
4      Weber  Christian      185.0       73.0

In [44]:
df.tail()

    lastname  firstname  height_cm  weight_kg
15  Schröder  Alexander      187.0       64.0
16   Neumann     Dennis        NaN       94.0
17     Braun      Frank        NaN        NaN
18   Schwarz        Tim      176.0       55.0
19    Krüger      Lukas      178.0       58.0

In [43]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 20 entries, 0 to 19
Data columns (total 4 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   lastname   20 non-null     object
 1   firstname  20 non-null     object
 2   height_cm  15 non-null     float64
 3   weight_kg  14 non-null     float64
dtypes: float64(2), object(2)
memory usage: 772.0+ bytes

## DataFrame Operatoren

* Siehe Python Grundlagen :)

In [ ]:
s1 = 'Hugo'
s2 = 'Meier'
s3 = s1 + ' ' + s2
s3

person = {'lastname': 'Meier', 'firstname': 'Hugo'}
name = person['firstname'] + ' ' + person['lastname']
name

people = [{'lastname': 'Meier', 'firstname': 'Hugo'}, {'lastname': 'Schneider', 'firstname': 'Hannah'}]
name = [person['firstname'] + ' ' + person['lastname'] for person in people]
name

    lastname  firstname  height_cm  weight_kg           fullname
0     Müller     Thomas      197.0        NaN      Thomas Müller
1    Schmidt    Michael      192.0       50.0    Michael Schmidt
2  Schneider    Andreas      191.0        NaN  Andreas Schneider
3    Fischer     Stefan      195.0       70.0     Stefan Fischer
4      Weber  Christian      185.0       73.0    Christian Weber

* Einführung der Series

In [ ]:
name_series = df['firstname'] + ' ' + df['lastname']
name_series
type(name_series)
df['lastname']
df['height_cm'] * 5
df['fullname'] = name_series

df.head()

* In der normalen Programmierung

In [63]:
df['fullname'] = df['firstname'] + ' ' + df['lastname']
df.head()

    lastname  firstname  height_cm  weight_kg           fullname
0     Müller     Thomas      197.0        NaN      Thomas Müller
1    Schmidt    Michael      192.0       50.0    Michael Schmidt
2  Schneider    Andreas      191.0        NaN  Andreas Schneider
3    Fischer     Stefan      195.0       70.0     Stefan Fischer
4      Weber  Christian      185.0       73.0    Christian Weber

* Eine Pandas Series ist quasi eine Spalte meines DataFrames
  * allerdings immer mit einem Index

## ToDo

* Berechnung einer Spalte, die den BMI der Person enthält

In [64]:
df['bmi'] = df['weight_kg']/((df['height_cm']/100)**2)
df.head()

    lastname  firstname  height_cm  weight_kg           fullname        bmi
0     Müller     Thomas      197.0        NaN      Thomas Müller        NaN
1    Schmidt    Michael      192.0       50.0    Michael Schmidt  13.563368
2  Schneider    Andreas      191.0        NaN  Andreas Schneider        NaN
3    Fischer     Stefan      195.0       70.0     Stefan Fischer  18.408941
4      Weber  Christian      185.0       73.0    Christian Weber  21.329438

### DataFrame und Kontrollstrukturen

* Schleifen

In [69]:
for element in df.values:
    print(f'{element} {type(element)}')

['Müller' 'Thomas' 197.0 nan 'Thomas Müller' nan] <class 'numpy.ndarray'>
['Schmidt' 'Michael' 192.0 50.0 'Michael Schmidt' 13.563368055555555] <class 'numpy.ndarray'>
['Schneider' 'Andreas' 191.0 nan 'Andreas Schneider' nan] <class 'numpy.ndarray'>
['Fischer' 'Stefan' 195.0 70.0 'Stefan Fischer' 18.408941485864563] <class 'numpy.ndarray'>
['Weber' 'Christian' 185.0 73.0 'Christian Weber' 21.32943754565376] <class 'numpy.ndarray'>
['Meyer' 'Markus' 183.0 67.0 'Markus Meyer' 20.00656932126967] <class 'numpy.ndarray'>
['Wagner' 'Daniel' nan 116.0 'Daniel Wagner' nan] <class 'numpy.ndarray'>
['Becker' 'Kevin' 193.0 113.0 'Kevin Becker' 30.336384869392468] <class 'numpy.ndarray'>
['Schulz' 'Sascha' 197.0 117.0 'Sascha Schulz' 30.14764616454946] <class 'numpy.ndarray'>
['Hoffmann' 'Jens' 193.0 nan 'Jens Hoffmann' nan] <class 'numpy.ndarray'>
['Koch' 'Oliver' nan 82.0 'Oliver Koch' nan] <class 'numpy.ndarray'>
['Bauer' 'Patrick' 165.0 93.0 'Patrick Bauer' 34.159779614325075] <class 'numpy.ndarray'>
['Richter' 'Jan' nan nan 'Jan Richter' nan] <class 'numpy.ndarray'>
['Klein' 'Tobias' 168.0 63.0 'Tobias Klein' 22.321428571428577] <class 'numpy.ndarray'>
['Wolf' 'Sebastian' 165.0 nan 'Sebastian Wolf' nan] <class 'numpy.ndarray'>
['Schröder' 'Alexander' 187.0 64.0 'Alexander Schröder' 18.301924561754696] <class 'numpy.ndarray'>
['Neumann' 'Dennis' nan 94.0 'Dennis Neumann' nan] <class 'numpy.ndarray'>
['Braun' 'Frank' nan nan 'Frank Braun' nan] <class 'numpy.ndarray'>
['Schwarz' 'Tim' 176.0 55.0 'Tim Schwarz' 17.75568181818182] <class 'numpy.ndarray'>
['Krüger' 'Lukas' 178.0 58.0 'Lukas Krüger' 18.30576947355132] <class 'numpy.ndarray'>

* Hinweis: Eine Iteration über einen DataFrame oder eine Series ist möglich, aber häufig gar nicht notwendig

### Abfragen

In [70]:
is_tall = df['height_cm'] > 190
is_tall

0      True
1      True
2      True
3      True
4     False
5     False
6     False
7      True
8      True
9      True
10    False
11    False
12    False
13    False
14    False
15    False
16    False
17    False
18    False
19    False
Name: height_cm, dtype: bool

In [73]:
df[is_tall]
filtered_dataframe = df[is_tall]
filtered_dataframe

    lastname firstname  height_cm  weight_kg           fullname        bmi
0     Müller    Thomas      197.0        NaN      Thomas Müller        NaN
1    Schmidt   Michael      192.0       50.0    Michael Schmidt  13.563368
2  Schneider   Andreas      191.0        NaN  Andreas Schneider        NaN
3    Fischer    Stefan      195.0       70.0     Stefan Fischer  18.408941
7     Becker     Kevin      193.0      113.0       Kevin Becker  30.336385
8     Schulz    Sascha      197.0      117.0      Sascha Schulz  30.147646
9   Hoffmann      Jens      193.0        NaN      Jens Hoffmann        NaN

* In der Praxis

In [74]:
df[df['height_cm'] > 190]

    lastname firstname  height_cm  weight_kg           fullname        bmi
0     Müller    Thomas      197.0        NaN      Thomas Müller        NaN
1    Schmidt   Michael      192.0       50.0    Michael Schmidt  13.563368
2  Schneider   Andreas      191.0        NaN  Andreas Schneider        NaN
3    Fischer    Stefan      195.0       70.0     Stefan Fischer  18.408941
7     Becker     Kevin      193.0      113.0       Kevin Becker  30.336385
8     Schulz    Sascha      197.0      117.0      Sascha Schulz  30.147646
9   Hoffmann      Jens      193.0        NaN      Jens Hoffmann        NaN

### ToDo
* Weisen Sie allen nicht-gesetzten Körpergrößen den Wert 181 zu, allen nicht gesetzten Körpergewichtete 77.7
* Einführung einer klassifizierenden Spalte 'height_category'
  * größer 190 -> 'tall'
  * 175 - 190 -> 'normal'
  * kleiner 175 -> small

In [88]:
df = pd.read_csv('people.csv')
df.fillna({'height_cm': 181}, inplace=True)
df.fillna({'weight_kg': 77.7}, inplace=True)
df['height_category'] = 'normal'
df.loc[df['height_cm'] > 190, 'height_category'] = 'tall'
df.loc[df['height_cm'] < 175, 'height_category'] = 'small'
df

     lastname  firstname  height_cm  weight_kg height_category
0      Müller     Thomas      197.0       77.7            tall
1     Schmidt    Michael      192.0       50.0            tall
2   Schneider    Andreas      191.0       77.7            tall
3     Fischer     Stefan      195.0       70.0            tall
4       Weber  Christian      185.0       73.0          normal
5       Meyer     Markus      183.0       67.0          normal
6      Wagner     Daniel      181.0      116.0          normal
7      Becker      Kevin      193.0      113.0            tall
8      Schulz     Sascha      197.0      117.0            tall
9    Hoffmann       Jens      193.0       77.7            tall
10       Koch     Oliver      181.0       82.0          normal
11      Bauer    Patrick      165.0       93.0           small
12    Richter        Jan      181.0       77.7          normal
13      Klein     Tobias      168.0       63.0           small
14       Wolf  Sebastian      165.0       77.7           small
15   Schröder  Alexander      187.0       64.0          normal
16    Neumann     Dennis      181.0       94.0          normal
17      Braun      Frank      181.0       77.7          normal
18    Schwarz        Tim      176.0       55.0          normal
19     Krüger      Lukas      178.0       58.0          normal