# Titanic-Datensatz

## Laden der einzelnen Datensätze

In [2]:
import pandas as pd
import numpy as np

In [3]:
titanic_part1_df = pd.read_csv('titanic.csv')
titanic_part1_df.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S

In [4]:
titanic_part2_incomplete_df = pd.read_csv('titanic_part2_incomplete.csv')
titanic_part2_incomplete_df.head()

,PassengerId,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,951,1,"Chaudanson, Miss. Victorine",female,36.0,0,0,PC 17608,262.3750,B61,C
1,952,3,"Dika, Mr. Mirko",male,17.0,0,0,349232,7.8958,NaN,S
2,953,2,"McCrae, Mr. Arthur Gordon",male,32.0,0,0,237216,13.5000,NaN,S
3,954,3,"Bjorklund, Mr. Ernst Herbert",male,18.0,0,0,347090,7.7500,NaN,S
4,955,3,"Bradley, Miss. Bridget Delia",female,22.0,0,0,334914,7.7250,NaN,Q

In [5]:
titanic_part2_survival_df = pd.read_csv('titanic_part2_survival.csv')
titanic_part2_survival_df.head()

   PassengerId  Survived
0          951         0
1          952         0
2          953         0
3          954         0
4          955         0

## Aufbauen des Gesamt-DataFrames

* Joinen / Mergen von incomplete und survival

In [6]:
titanic_part2_df = pd.merge(titanic_part2_incomplete_df, titanic_part2_survival_df, how='inner', on='PassengerId')
titanic_part2_df.head()

,PassengerId,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked,Survived
0,951,1,"Chaudanson, Miss. Victorine",female,36.0,0,0,PC 17608,262.3750,B61,C,0
1,952,3,"Dika, Mr. Mirko",male,17.0,0,0,349232,7.8958,NaN,S,0
2,953,2,"McCrae, Mr. Arthur Gordon",male,32.0,0,0,237216,13.5000,NaN,S,0
3,954,3,"Bjorklund, Mr. Ernst Herbert",male,18.0,0,0,347090,7.7500,NaN,S,0
4,955,3,"Bradley, Miss. Bridget Delia",female,22.0,0,0,334914,7.7250,NaN,Q,0

* Konkatination des Datensatzes
    * unter fortlaufendem Index

In [8]:
df = pd.concat([titanic_part1_df, titanic_part2_df], ignore_index=True)
df.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S

In [9]:
df.shape

(1308, 12)

## Exploration

In [10]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1308 entries, 0 to 1307
Data columns (total 12 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   PassengerId  1308 non-null   int64
 1   Survived     1308 non-null   int64
 2   Pclass       1308 non-null   int64
 3   Name         1308 non-null   object
 4   Sex          1308 non-null   object
 5   Age          1045 non-null   float64
 6   SibSp        1308 non-null   int64
 7   Parch        1308 non-null   int64
 8   Ticket       1308 non-null   object
 9   Fare         1307 non-null   float64
 10  Cabin        295 non-null    object
 11  Embarked     1306 non-null   object
dtypes: float64(2), int64(5), object(5)
memory usage: 122.8+ KB

* Bedeutung der Spalten
    * PassengerId
    * Survived: 0=verstorben, 1=überlebt
    * PClass: 1.-4. Klasse
    * Name
    * Sex: male / female
    * Age > 0, < 125
    * SibSp = Siblings (Verwandte) / Spouse (PartnerIn)
    * Parch = Parents / Children
    * Ticket = Identifier, Zufallszahl, Reisebüro, ...
    * Fare = Preis
    * Cabin = Kabinennummer, beginnend mit einem Zeichen im Schiiffsbereich A-F und einer Nummer
    * Embarked = Zustiegspunkte, (S=Southhampton, Q = Queenstown, C = Cherbourg)

In [19]:
df.nunique()

PassengerId    1308
Survived          2
Pclass            3
Name           1306
Sex               2
Age              98
SibSp             7
Parch             8
Ticket          928
Fare            281
Cabin           186
Embarked          3
dtype: int64

In [20]:
df['Embarked'].unique()

array(['S', 'C', 'Q', nan], dtype=object)

* Identifikation von NaNs

In [24]:
df[df['Embarked'].isna()]

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
61,62,1,1,"Icard, Miss. Amelie",female,38.0,0,0,113572,80.0,B28,NaN
829,830,1,1,"Stone, Mrs. George Nelson (Martha Evelyn)",female,62.0,0,0,113572,80.0,B28,NaN

* Plausibilitäten

In [26]:
f'Anzahl Alter < 0: {(df['Age'] < 0).sum()}'

'Anzahl Alter < 0: 0'

In [28]:
f'Anzahl Alter > 125: {(df['Age'] > 125).sum()}'

'Anzahl Alter > 125: 0'

* Zusammenfassung
    * Kategorien sind Survived, Sex, Embarked, Pclass
    * Ticket-Spalte ist unnötig
    * PassengerId ist auch als Index geeignet
    * Cabin hat zwei Teile: Bereich = Kategorie, Kabinennummer im Bereich
    * Nicht gesetzte Werte insbesondere im Age
        * Umgang: Löschen von Datensätzen, Drop der Spalte, Setzen mit einem vernünftigen Wert