Pandas DataFrames

## Pandas Series

In [1]:
import numpy as np
import pandas as pd

In [2]:
my_series = pd.Series( data = [2,3,5,4],             # Data
                       index= ['a', 'b', 'c', 'd'])  # Indexes

my_series

a    2
b    3
c    5
d    4
dtype: int64

In [3]:
my_dict = {"x": 2, "a": 5, "b": 4, "c": 8}

my_series2 = pd.Series(my_dict)

my_series2

x    2
a    5
b    4
c    8
dtype: int64

In [4]:
my_series["a"]

np.int64(2)

In [5]:
my_series[0]

C:\Users\raine\AppData\Local\Temp\ipykernel_7468\350777571.py:1: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  my_series[0]

np.int64(2)

In [6]:
my_series[1:3]

b    3
c    5
dtype: int64

In [7]:
my_series + my_series

a     4
b     6
c    10
d     8
dtype: int64

In [8]:
my_series + my_series2

a     7.0
b     7.0
c    13.0
d     NaN
x     NaN
dtype: float64

In [9]:
np.mean(my_series)        # numpy array functions generally work on series

np.float64(3.5)

## DataFrame Creation and Indexing

In [10]:
# Create a dictionary with some different data types as values

my_dict = {"name" : ["Joe","Bob","Frans"],
           "age" : np.array([10,15,20]),
           "weight" : (75,123,239),
           "height" : pd.Series([4.5, 5, 6.1], 
                                index=["Joe","Bob","Frans"]),
           "siblings" : 1,
           "gender" : "M"}

df = pd.DataFrame(my_dict)   # Convert the dict to DataFrame

df                           # Show the DataFrame

        name  age  weight  height  siblings gender
Joe      Joe   10      75     4.5         1      M
Bob      Bob   15     123     5.0         1      M
Frans  Frans   20     239     6.1         1      M

In [11]:
my_dict2 = {"name" : ["Joe","Bob","Frans"],
           "age" : np.array([10,15,20]),
           "weight" : (75,123,239),
           "height" :[4.5, 5, 6.1],
           "siblings" : 1,
           "gender" : "M"}

df2 = pd.DataFrame(my_dict2)   # Convert the dict to DataFrame

df2                            # Show the DataFrame

    name  age  weight  height  siblings gender
0    Joe   10      75     4.5         1      M
1    Bob   15     123     5.0         1      M
2  Frans   20     239     6.1         1      M

In [12]:
df2 = pd.DataFrame(my_dict2,
                   index = my_dict["name"] )

df2

        name  age  weight  height  siblings gender
Joe      Joe   10      75     4.5         1      M
Bob      Bob   15     123     5.0         1      M
Frans  Frans   20     239     6.1         1      M

In [13]:
# Get a column by name

df2["weight"]

Joe       75
Bob      123
Frans    239
Name: weight, dtype: int64

In [14]:
df2.weight

Joe       75
Bob      123
Frans    239
Name: weight, dtype: int64

In [15]:
# Delete a column

del df2['name']

In [16]:
# Add a new column

df2["IQ"] = [130, 105, 115]

df2

       age  weight  height  siblings gender   IQ
Joe     10      75     4.5         1      M  130
Bob     15     123     5.0         1      M  105
Frans   20     239     6.1         1      M  115

In [17]:
df2["Married"] = False

df2

       age  weight  height  siblings gender   IQ  Married
Joe     10      75     4.5         1      M  130    False
Bob     15     123     5.0         1      M  105    False
Frans   20     239     6.1         1      M  115    False

In [18]:

df2["College"] = pd.Series(["Harvard"],
                           index=["Frans"])

df2

       age  weight  height  siblings gender   IQ  Married  College
Joe     10      75     4.5         1      M  130    False      NaN
Bob     15     123     5.0         1      M  105    False      NaN
Frans   20     239     6.1         1      M  115    False  Harvard

In [19]:
df2.loc["Joe"]          # Select row "Joe"

age            10
weight         75
height        4.5
siblings        1
gender          M
IQ            130
Married     False
College       NaN
Name: Joe, dtype: object

In [20]:
df2.loc["Joe","IQ"]     # Select row "Joe" and column "IQ"

np.int64(130)

In [21]:
df2.loc["Joe":"Bob" , "IQ":"College"]   # Slice by label

      IQ  Married College
Joe  130    False     NaN
Bob  105    False     NaN

In [22]:
df2.iloc[0]          # Get row 0

age            10
weight         75
height        4.5
siblings        1
gender          M
IQ            130
Married     False
College       NaN
Name: Joe, dtype: object

In [23]:
df2.iloc[0, 5]       # Get row 0, column 5

np.int64(130)

In [24]:
df2.iloc[0:2, 5:8]   # Slice by numeric row and column index

      IQ  Married College
Joe  130    False     NaN
Bob  105    False     NaN

In [25]:
boolean_index = [False, True, True]  

df2[boolean_index]

       age  weight  height  siblings gender   IQ  Married  College
Bob     15     123     5.0         1      M  105    False      NaN
Frans   20     239     6.1         1      M  115    False  Harvard

In [26]:
# Create a boolean sequence with a logical comparison
boolean_index = df2["age"] > 12

# Use the index to get the rows where age > 12
df2[boolean_index]

       age  weight  height  siblings gender   IQ  Married  College
Bob     15     123     5.0         1      M  105    False      NaN
Frans   20     239     6.1         1      M  115    False  Harvard

In [27]:
df2[ df2["age"] > 12 ]

       age  weight  height  siblings gender   IQ  Married  College
Bob     15     123     5.0         1      M  105    False      NaN
Frans   20     239     6.1         1      M  115    False  Harvard

## Exploring DataFrames

In [29]:
titanic_train = pd.read_csv("titanic.csv")

type(titanic_train)

pandas.core.frame.DataFrame

In [ ]:
titanic_train.shape      # Check dimensions

In [ ]:
titanic_train.head(6)    # Check the first 6 rows

In [ ]:
titanic_train.tail(6)   # Check the last 6 rows

In [ ]:
titanic_train.index = titanic_train["Name"]  # Set index to name
del titanic_train["Name"]                    # Delete name column

print(titanic_train.index[0:10])             # Print new indexes

In [ ]:
titanic_train.columns

In [ ]:
titanic_train.describe()    # Summarize the first 6 columns

In [ ]:
np.mean(titanic_train,
        axis=0)          # Get the mean of each numeric column

In [ ]:
titanic_train.info()