Pandas DataFrames

## Pandas Series

* Importieren der notwendigen Bibliotheken

In [1]:
import numpy as np
import pandas as pd

* Eine Pandas Series ist vergleichbar zu einem Dictionary

In [7]:
my_series = pd.Series( data = [2,3,5,4],             # Data
                       index= ['a', 'b', 'c', 'd'])  # Indexes

my_series

a    2
b    3
c    5
d    4
dtype: int64

In [8]:
my_dict = {"x": 2, "a": 5, "b": 4, "c": 8}

my_series2 = pd.Series(my_dict)

my_series2

x    2
a    5
b    4
c    8
dtype: int64

In [9]:
my_series["a"]

np.int64(2)

* Eine Series hat auch immer einen fortlaufenden, numerischen Index
  * damit verhält sich die Series wie eine Liste

In [5]:
my_series[0]

C:\Users\raine\AppData\Local\Temp\ipykernel_7468\350777571.py:1: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  my_series[0]

np.int64(2)

In [6]:
my_series[1:3]

b    3
c    5
dtype: int64

In [11]:
my_series + my_series

a     4
b     6
c    10
d     8
dtype: int64

In [ ]:
my_series + my_series2

a    12.0
b    11.0
c    21.0
d     NaN
x     NaN
dtype: float64

In [13]:
np.mean(my_series)        # numpy array functions generally work on series

np.float64(3.5)

## DataFrame Creation and Indexing

* Ein DataFrame ist auch wie ein Dictionary aufzufassen

In [73]:
# Create a dictionary with some different data types as values

my_dict = {"name" : ["Joe","Bob","Frans"],
           "age" : np.array([10,15,20]),
           "weight" : (75,123,239),
           "height" : pd.Series([4.5, 5, 6.1], 
                                index=["Joe","Bob","Frans"]),
           "siblings" : 1,
           "gender" : "M"}

df = pd.DataFrame(my_dict)   # Convert the dict to DataFrame

df                           # Show the DataFrame

        name  age  weight  height  siblings gender
Joe      Joe   10      75     4.5         1      M
Bob      Bob   15     123     5.0         1      M
Frans  Frans   20     239     6.1         1      M

In [74]:
my_dict2 = {"name" : ["Joe","Bob","Frans"],
           "age" : np.array([10,15,20]),
           "weight" : (75,123,239),
           "height" :[4.5, 5, 6.1],
           "siblings" : 1,
           "gender" : "M"}

df2 = pd.DataFrame(my_dict2)   # Convert the dict to DataFrame

df2                            # Show the DataFrame

    name  age  weight  height  siblings gender
0    Joe   10      75     4.5         1      M
1    Bob   15     123     5.0         1      M
2  Frans   20     239     6.1         1      M

In [75]:
df2 = pd.DataFrame(my_dict2,
                   index = my_dict["name"] )

df2

        name  age  weight  height  siblings gender
Joe      Joe   10      75     4.5         1      M
Bob      Bob   15     123     5.0         1      M
Frans  Frans   20     239     6.1         1      M

In [76]:
# Get a column by name

df2["weight"]

Joe       75
Bob      123
Frans    239
Name: weight, dtype: int64

In [77]:
df2.weight

Joe       75
Bob      123
Frans    239
Name: weight, dtype: int64

In [78]:
# Delete a column

del df2['name']

In [79]:
# Add a new column

df2["IQ"] = [130, 105, 115]

df2

       age  weight  height  siblings gender   IQ
Joe     10      75     4.5         1      M  130
Bob     15     123     5.0         1      M  105
Frans   20     239     6.1         1      M  115

In [80]:
df2["Married"] = False

df2

       age  weight  height  siblings gender   IQ  Married
Joe     10      75     4.5         1      M  130    False
Bob     15     123     5.0         1      M  105    False
Frans   20     239     6.1         1      M  115    False

In [81]:

df2["College"] = pd.Series(["Harvard"],
                           index=["Frans"])

df2

       age  weight  height  siblings gender   IQ  Married  College
Joe     10      75     4.5         1      M  130    False      NaN
Bob     15     123     5.0         1      M  105    False      NaN
Frans   20     239     6.1         1      M  115    False  Harvard

* Selektion einer Zeile

In [82]:
df2.loc["Joe"]          # Select row "Joe"

age            10
weight         75
height        4.5
siblings        1
gender          M
IQ            130
Married     False
College       NaN
Name: Joe, dtype: object

In [83]:
df2.loc["Joe","IQ"]     # Select row "Joe" and column "IQ"

np.int64(130)

In [84]:
df2.loc["Joe":"Bob" , "IQ":"College"]   # Slice by label

      IQ  Married College
Joe  130    False     NaN
Bob  105    False     NaN

In [85]:
df2.iloc[0]          # Get row 0

age            10
weight         75
height        4.5
siblings        1
gender          M
IQ            130
Married     False
College       NaN
Name: Joe, dtype: object

In [86]:
df2.iloc[0, 5]       # Get row 0, column 5

np.int64(130)

In [87]:
df2.iloc[0:2, 5:8]   # Slice by numeric row and column index

      IQ  Married College
Joe  130    False     NaN
Bob  105    False     NaN

* Etwas Neues: Liste von Booleans als Index-Kriterium

In [88]:
boolean_index = [False, True, True]  

df2[boolean_index]

       age  weight  height  siblings gender   IQ  Married  College
Bob     15     123     5.0         1      M  105    False      NaN
Frans   20     239     6.1         1      M  115    False  Harvard

In [89]:
# Create a boolean sequence with a logical comparison
boolean_index = df2["age"] > 12
# boolean_index
# Use the index to get the rows where age > 12
df2[boolean_index]

       age  weight  height  siblings gender   IQ  Married  College
Bob     15     123     5.0         1      M  105    False      NaN
Frans   20     239     6.1         1      M  115    False  Harvard

* Gängige Kompaktform
  * gewöhnungsbedürftig zu Lesen und Schreiben

In [90]:
df2[ df2["age"] > 12 ]

       age  weight  height  siblings gender   IQ  Married  College
Bob     15     123     5.0         1      M  105    False      NaN
Frans   20     239     6.1         1      M  115    False  Harvard

## Exploring DataFrames

In [91]:
titanic_df = pd.read_csv("titanic.csv")

type(titanic_df)

pandas.core.frame.DataFrame

In [92]:
titanic_df.shape      # Check dimensions

(891, 12)

In [95]:
titanic_df .head(6)  # Check the first 6 rows

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S
5,6,0,3,"Moran, Mr. James",male,NaN,0,0,330877,8.4583,NaN,Q

In [96]:
titanic_df.tail(6)   # Check the last 6 rows

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
885,886,0,3,"Rice, Mrs. William (Margaret Norton)",female,39.0,0,5,382652,29.125,NaN,Q
886,887,0,2,"Montvila, Rev. Juozas",male,27.0,0,0,211536,13.000,NaN,S
887,888,1,1,"Graham, Miss. Margaret Edith",female,19.0,0,0,112053,30.000,B42,S
888,889,0,3,"Johnston, Miss. Catherine Helen ""Carrie""",female,NaN,1,2,W./C. 6607,23.450,NaN,S
889,890,1,1,"Behr, Mr. Karl Howell",male,26.0,0,0,111369,30.000,C148,C
890,891,0,3,"Dooley, Mr. Patrick",male,32.0,0,0,370376,7.750,NaN,Q

In [97]:
titanic_df.index = titanic_df["Name"]  # Set index to name
del titanic_df["Name"]                    # Delete name column

print(titanic_df.index[0:10])             # Print new indexes

Index(['Braund, Mr. Owen Harris',
       'Cumings, Mrs. John Bradley (Florence Briggs Thayer)',
       'Heikkinen, Miss. Laina',
       'Futrelle, Mrs. Jacques Heath (Lily May Peel)',
       'Allen, Mr. William Henry', 'Moran, Mr. James',
       'McCarthy, Mr. Timothy J', 'Palsson, Master. Gosta Leonard',
       'Johnson, Mrs. Oscar W (Elisabeth Vilhelmina Berg)',
       'Nasser, Mrs. Nicholas (Adele Achem)'],
      dtype='object', name='Name')

In [98]:
titanic_df.columns

Index(['PassengerId', 'Survived', 'Pclass', 'Sex', 'Age', 'SibSp', 'Parch',
       'Ticket', 'Fare', 'Cabin', 'Embarked'],
      dtype='object')

In [99]:
titanic_df.describe()    # Summarize the first 6 columns

,PassengerId,Survived,Pclass,Age,SibSp,Parch,Fare
count,891.000000,891.000000,891.000000,714.000000,891.000000,891.000000,891.000000
mean,446.000000,0.383838,2.308642,29.699118,0.523008,0.381594,32.204208
std,257.353842,0.486592,0.836071,14.526497,1.102743,0.806057,49.693429
min,1.000000,0.000000,1.000000,0.420000,0.000000,0.000000,0.000000
25%,223.500000,0.000000,2.000000,20.125000,0.000000,0.000000,7.910400
50%,446.000000,0.000000,3.000000,28.000000,0.000000,0.000000,14.454200
75%,668.500000,1.000000,3.000000,38.000000,1.000000,0.000000,31.000000
max,891.000000,1.000000,3.000000,80.000000,8.000000,6.000000,512.329200

In [102]:
titanic_df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 891 entries, Braund, Mr. Owen Harris to Dooley, Mr. Patrick
Data columns (total 11 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   PassengerId  891 non-null    int64
 1   Survived     891 non-null    int64
 2   Pclass       891 non-null    int64
 3   Sex          891 non-null    object
 4   Age          714 non-null    float64
 5   SibSp        891 non-null    int64
 6   Parch        891 non-null    int64
 7   Ticket       891 non-null    object
 8   Fare         891 non-null    float64
 9   Cabin        204 non-null    object
 10  Embarked     889 non-null    object
dtypes: float64(2), int64(5), object(4)
memory usage: 83.5+ KB