# Die Pandas Bibliothek

In [77]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

%matplotlib inline

## Lese-Methoden

### Lesen einer lokalen CSV-Datei

In [78]:
df = pd.read_csv('people.csv')
df.head()

               Name  Weight  Height
0      Anna Neumann    55.8   165.0
1        Ben Wagner    78.6   180.0
2       Carla Weber    60.5     NaN
3     David Schmidt    85.5   185.0
4  Elena Zimmermann    52.5   160.0

### Lesen einer lokalen JSON-Datei

In [79]:
df = pd.read_json('people.json')
df.head()

   id  lastname firstname gender  height
0   1  Sawitzki    Rainer      m     183
1   2     Meier      Hans      m     163
2   3   Metzger     Georg      m     190
3   4   Metzger    Frieda      f     167
4   5  Hoffmann     Hanna      f     155

### Lesen eines RESTful WebServices

In [80]:
df = pd.read_json('http://javacream.eu:8080/people')
df.head()

   id  lastname firstname gender  height
0   1  Sawitzki    Rainer      m     183
1   2     Meier      Hans      m     163
2   3   Metzger     Georg      m     190
3   4   Metzger    Frieda      f     167
4   5  Hoffmann     Hanna      f     155

### Lesen einer CSV-Datei vom Internet

In [81]:
df = pd.read_csv('https://raw.githubusercontent.com/lawlesst/vivo-sample-data/refs/heads/master/data/csv/people.csv')
df.head()

,person_ID,name,first,last,middle,email,phone,fax,title
0,3130,"Burks, Rosella",Rosella,Burks,NaN,BurksR@univ.edu,963.555.1253,963.777.4065,Professor
1,3297,"Avila, Damien",Damien,Avila,NaN,AvilaD@univ.edu,963.555.1352,963.777.7914,Professor
2,3547,"Olsen, Robin",Robin,Olsen,NaN,OlsenR@univ.edu,963.555.1378,963.777.9262,Assistant Professor
3,1538,"Moises, Edgar Estes",Edgar,Moises,Estes,MoisesE@univ.edu,963.555.2731x3565,963.777.8264,Professor
4,2941,"Brian, Heath Pruitt",Heath,Brian,Pruitt,BrianH@univ.edu,963.555.2800,963.777.7249,Associate Curator

### Lesen von Daten aus einer Datenbank

In [82]:
import mysql.connector

connection = mysql.connector.connect(
    host='javacream.eu', port=3406, username='user', password='user', database='javacream'
)

df = pd.read_sql('select * from PEOPLE', connection)
df.head()

C:\Users\raine\AppData\Local\Temp\ipykernel_8684\382096201.py:7: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  df = pd.read_sql('select * from PEOPLE', connection)

   id firstname lastname  height  weight
0   1    Stacey   Miller    1.68    92.0
1   2     Carla   Gentry    1.68    85.4
2   3      Emma  Harding    1.75    98.2
3   4  Jeanette    Lopez    1.58    73.8
4   5    Edward    White    1.63    68.5

## Datenexploration

* Siehe Diamonds
  * head, tail
  * info
  * describe
* Neu: Prüfung auf unsaubere Daten
  * None-Werte
  * NaN-Werte

In [83]:
df = pd.read_csv('people.csv')
df.isna()

     Name  Weight  Height
0   False   False   False
1   False   False   False
2   False   False    True
3   False   False   False
4   False   False   False
5   False   False   False
6   False   False   False
7   False   False   False
8   False   False   False
9   False   False   False
10  False   False   False
11  False   False   False
12  False   False   False
13  False    True   False
14  False    True    True
15  False   False   False
16  False   False   False
17  False    True   False
18  False   False   False
19  False   False   False

In [84]:
df.isna().sum()

Name      0
Weight    3
Height    2
dtype: int64

In [85]:
df['Height'].isna()

0     False
1     False
2      True
3     False
4     False
5     False
6     False
7     False
8     False
9     False
10    False
11    False
12    False
13    False
14     True
15    False
16    False
17    False
18    False
19    False
Name: Height, dtype: bool

In [86]:
df['Height'].isna().sum()

np.int64(2)

* Selektion mit dem DataFrame
  * Wie ein Dictionary selektiert der DataFrame auf Spalten

In [87]:
df['Height']

0     165.0
1     180.0
2       NaN
3     185.0
4     160.0
5     190.0
6     172.0
7     178.0
8     167.0
9     182.0
10    166.0
11    179.0
12    171.0
13    187.0
14      NaN
15    181.0
16    175.0
17    176.0
18    184.0
19    168.0
Name: Height, dtype: float64

* Selektion mit einem Boolean Vektor

In [88]:
criterion_vector = df['Height'].isna()
criterion_vector

0     False
1     False
2      True
3     False
4     False
5     False
6     False
7     False
8     False
9     False
10    False
11    False
12    False
13    False
14     True
15    False
16    False
17    False
18    False
19    False
Name: Height, dtype: bool

In [89]:
df[criterion_vector]

              Name  Weight  Height
2      Carla Weber    60.5     NaN
14  Olivia Schäfer     NaN     NaN

In [90]:
df[df['Height'].isna()]

              Name  Weight  Height
2      Carla Weber    60.5     NaN
14  Olivia Schäfer     NaN     NaN

In [91]:
df[df['Height'] > 180]

               Name  Weight  Height
3     David Schmidt    85.5   185.0
5     Felix Schäfer    90.5   190.0
9       Jonas Bauer    80.3   182.0
13        Nico Wolf     NaN   187.0
15      Paul Müller    79.2   181.0
18  Samuel Schröder    83.7   184.0

In [92]:
df['Name'][(df['Height'] > 180) & (df['Weight'] < 85)]

9         Jonas Bauer
15        Paul Müller
18    Samuel Schröder
Name: Name, dtype: object

## Cleanup

### Droppen von Daten mit NaN

In [99]:
df.dropna()

                Name  Weight  Height
0       Anna Neumann    55.8   165.0
1         Ben Wagner    78.6   180.0
3      David Schmidt    85.5   185.0
4   Elena Zimmermann    52.5   160.0
5      Felix Schäfer    90.5   190.0
6    Gina Zimmermann    65.6   172.0
7    Hannes Hoffmann    72.4   178.0
8        Isabel Koch    58.8   167.0
9        Jonas Bauer    80.3   182.0
10     Klara Schäfer    56.7   166.0
11     Lukas Fischer    76.4   179.0
12       Maria Weber    62.1   171.0
15       Paul Müller    79.2   181.0
16     Quinn Neumann    68.8   175.0
18   Samuel Schröder    83.7   184.0
19      Tina Fischer    59.7   168.0

In [100]:
df.dropna(axis=1)

                Name
0       Anna Neumann
1         Ben Wagner
2        Carla Weber
3      David Schmidt
4   Elena Zimmermann
5      Felix Schäfer
6    Gina Zimmermann
7    Hannes Hoffmann
8        Isabel Koch
9        Jonas Bauer
10     Klara Schäfer
11     Lukas Fischer
12       Maria Weber
13         Nico Wolf
14    Olivia Schäfer
15       Paul Müller
16     Quinn Neumann
17      Ronja Müller
18   Samuel Schröder
19      Tina Fischer

* Bisher wurde der DataFrame nicht geändert!

In [101]:
df

                Name  Weight  Height
0       Anna Neumann    55.8   165.0
1         Ben Wagner    78.6   180.0
2        Carla Weber    60.5     NaN
3      David Schmidt    85.5   185.0
4   Elena Zimmermann    52.5   160.0
5      Felix Schäfer    90.5   190.0
6    Gina Zimmermann    65.6   172.0
7    Hannes Hoffmann    72.4   178.0
8        Isabel Koch    58.8   167.0
9        Jonas Bauer    80.3   182.0
10     Klara Schäfer    56.7   166.0
11     Lukas Fischer    76.4   179.0
12       Maria Weber    62.1   171.0
13         Nico Wolf     NaN   187.0
14    Olivia Schäfer     NaN     NaN
15       Paul Müller    79.2   181.0
16     Quinn Neumann    68.8   175.0
17      Ronja Müller     NaN   176.0
18   Samuel Schröder    83.7   184.0
19      Tina Fischer    59.7   168.0

* Änderung des originalen DataFrames mit inplace= True

In [102]:
df.dropna(inplace=True)
df

                Name  Weight  Height
0       Anna Neumann    55.8   165.0
1         Ben Wagner    78.6   180.0
3      David Schmidt    85.5   185.0
4   Elena Zimmermann    52.5   160.0
5      Felix Schäfer    90.5   190.0
6    Gina Zimmermann    65.6   172.0
7    Hannes Hoffmann    72.4   178.0
8        Isabel Koch    58.8   167.0
9        Jonas Bauer    80.3   182.0
10     Klara Schäfer    56.7   166.0
11     Lukas Fischer    76.4   179.0
12       Maria Weber    62.1   171.0
15       Paul Müller    79.2   181.0
16     Quinn Neumann    68.8   175.0
18   Samuel Schröder    83.7   184.0
19      Tina Fischer    59.7   168.0

In [103]:
df = pd.read_csv('people.csv')

### Füllen der NaN-Werte

* Fixer Wert

In [105]:
df.fillna({'Weight': 66.6, 'Height': 177})

                Name  Weight  Height
0       Anna Neumann    55.8   165.0
1         Ben Wagner    78.6   180.0
2        Carla Weber    60.5   177.0
3      David Schmidt    85.5   185.0
4   Elena Zimmermann    52.5   160.0
5      Felix Schäfer    90.5   190.0
6    Gina Zimmermann    65.6   172.0
7    Hannes Hoffmann    72.4   178.0
8        Isabel Koch    58.8   167.0
9        Jonas Bauer    80.3   182.0
10     Klara Schäfer    56.7   166.0
11     Lukas Fischer    76.4   179.0
12       Maria Weber    62.1   171.0
13         Nico Wolf    66.6   187.0
14    Olivia Schäfer    66.6   177.0
15       Paul Müller    79.2   181.0
16     Quinn Neumann    68.8   175.0
17      Ronja Müller    66.6   176.0
18   Samuel Schröder    83.7   184.0
19      Tina Fischer    59.7   168.0

### Exkurs: Schreiben des DataFrames

In [106]:
filled = df.fillna({'Weight': 66.6, 'Height': 177})
filled.to_csv('people_filled.csv')

* Extrapolation der Werte Vorgänger / Nachfolger
  * Hinweis: Für dieses Beispiel Unsinn

In [107]:
df.ffill()

                Name  Weight  Height
0       Anna Neumann    55.8   165.0
1         Ben Wagner    78.6   180.0
2        Carla Weber    60.5   180.0
3      David Schmidt    85.5   185.0
4   Elena Zimmermann    52.5   160.0
5      Felix Schäfer    90.5   190.0
6    Gina Zimmermann    65.6   172.0
7    Hannes Hoffmann    72.4   178.0
8        Isabel Koch    58.8   167.0
9        Jonas Bauer    80.3   182.0
10     Klara Schäfer    56.7   166.0
11     Lukas Fischer    76.4   179.0
12       Maria Weber    62.1   171.0
13         Nico Wolf    62.1   187.0
14    Olivia Schäfer    62.1   187.0
15       Paul Müller    79.2   181.0
16     Quinn Neumann    68.8   175.0
17      Ronja Müller    68.8   176.0
18   Samuel Schröder    83.7   184.0
19      Tina Fischer    59.7   168.0